name: Build

on:
  push:
    paths-ignore: [ "**.md", "**.py", "**.txt" ]
    branches: [ "master", "release/**" ]
  pull_request:
    paths-ignore: [ "**.md", "**.py", "**.txt" ]
    branches: [ "master", "release/**" ]

jobs:
  windows_build:
    name: "Build - Windows x64"
    runs-on: windows-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup MSBuild"
        uses: microsoft/setup-msbuild@v1.1.3

      - name: "Setup xmake"
        uses: xmake-io/github-action-setup-xmake@v1.0.13
        with:
          xmake-version: latest

      - name: "Configure xmake"
        run: "xmake f -m release -y"

      - name: "Build using xmake"
        run: "xmake"

      - name: "Create installable package"
        run: "xmake install"
